### ISSUE TITLE
Example script

### ISSUE THREAD

**Issue by junsu-kim97** [2016choang/sfl#1]
Hi, Christopher Hoang

Thanks for open-sourcing your implementation.

I really enjoyed reading your paper, and I like the idea.

By the way, I am struggling how to reproduce the results in the paper.

So, I wonder whether you could provide some example scripts to reproduce the results for Minigrid or VizDoom.

Thanks in advance.

Best,

Junsu.

**Comment by 2016choang** [comment]
Hi Junsu,

I am glad you liked the paper! I have added some instructions and example commands in the README here: https://github.com/2016choang/sfl/blob/master/README.md.

Please let me know if you have other questions.

Best,
Chris

**Comment by junsu-kim97** [comment]
Thanks for the instructions and example commands !

The open-sourced code along with newly updated instructions would be very helpful for future research a lot !

Best, 
Junsu
