### ISSUE TITLE
Can't find the "minigrid-configs" directory and base-4rooms.json file

### ISSUE THREAD

**Issue by Lai-Chien-Chun** [2016choang/sfl#2]
Hello, Hoang
I'm trying to run your work recently. I followed your instructions in README.md to build the environment and install minigrid and rlpyt.
After that, when i try to do the Example run command for MiniGrid's MultiRoom environment, but there is no "minigrid-configs" directory and "base-4rooms.json" file. 
I got the message:
FileNotFoundError: [Errno 2] No such file or directory: 'experiments/minigrid-configs/multiroom/base-4rooms.json'
What step did i miss?
Thank you so much!
Best,

Kevin

**Comment by 2016choang** [comment]
Hi @Lai-Chien-Chun, you have to first check out the `update-minigrid` branch.
